name: Build and Push Docker Image with Kaniko

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: arc-runner-set

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kaniko environment
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

      - name: Build and push Docker image with Kaniko
        uses: gcr.io/kaniko-project/executor:latest
        with:
          args: >
            --context ${{ github.workspace }}
            --dockerfile ${{ github.workspace }}/Dockerfile
            --destination docker.io/kraskmax/git-samle:latest
