name: Build and Push Docker Image with Kaniko

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  login:
    runs-on: arc-runner-set
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  build:
    runs-on: arc-runner-set
    steps:
      - name: kaniko-action
        uses: int128/kaniko-action@v1.43.0
